#DB connection Info

#DB Docker ver (Service Name 'db' inside docker-compose)
db.driver.Class=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://db:3306/kopodb?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
db.username=kopouser
db.password=kopouser

#DB Local ver (for Windows)
#db.driver.Class=com.mysql.cj.jdbc.Driver
#db.url=jdbc:mysql://localhost:3307/kopodb?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
#db.username=kopouser
#db.password=kopouser
