CREATE DATABASE IF NOT EXISTS kopodb;
USE kopodb;

CREATE TABLE IF NOT EXISTS student_scores (
    id INT AUTO_INCREMENT PRIMARY KEY,
    student_name VARCHAR(50) NOT NULL,
    kor INT NOT NULL DEFAULT 0,
    eng INT NOT NULL DEFAULT 0,
    math INT NOT NULL DEFAULT 0,
    total_score INT NOT NULL DEFAULT 0,
    avg_score DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    student_rank INT DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
